[python]
format = 'via [${symbol}(\($virtualenv\) )]($style)'
symbol = 'ğŸ'

[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = false

[time]
disabled = false
format = 'ğŸ•™ [$time]($style) '
time_format = '%F %T'